AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - "bin/*"
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - db/schema.rb
    - "tmp/**/*"
    - Gemfile
    - Rakefile

Rails:
  Enabled: true

Style/Documentation:
  Exclude:
    - "app/controllers/*_controller.rb"
    - "app/helpers/**/*_helper.rb"
    - "app/mailers/**/*_mailer.rb"
    - "app/models/**/*"
    - "app/jobs/**/*"
    - "app/uploaders/**/*"
    - "config/**/*"
    - "db/**/*"
    - "test/**/*"

LineLength:
  Max: 120
  Exclude:
    - "config/initializers/devise.rb"

Style/RedundantSelf:
  Exclude:
    - config/initializers/status_page.rb

Metrics/AbcSize:
  Exclude:
    - "config/initializers/*"
    - "app/controllers/**/*"
    - "app/uploaders/*"
    - "db/migrate/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 12
  Exclude:
    - "config/initializers/*"
    - "db/migrate/*"
    - "test/**/*"
