# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ec36f6f7e03a6aa05c2f147bd8c54a0ee35cd69d408cc70e16e78a4504db355ae8b1b420838475c94c6252cc531eb872374a630808a5a47c042f74db6f72a3a

test:
  secret_key_base: d249ae733b31daeff170055f8b0a8f5912cb5c439203fedbd91f8a9aedfc5328bea0056987562d2198dbeef0620b947d41781265ff73d0f1811a9567b81d240b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
